name: Example workflow

on:
  workflow_dispatch:

jobs:
  example:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Typst
        uses: yusancky/setup-typst@issue-8
        with:
          version: 'v0.2.0'
      - run: |
          cd c:\\typst
          tree . -F
          echo $GITHUB_PATH
      - name: Compile Typst file
        run: typst compile file.typ
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: file.pdf
          path: file.pdf
          if-no-files-found: error
